### ISSUE TITLE
npm name "ecommerce"

### ISSUE THREAD

**Issue by jonschlinkert** [hanzo-io/hanzo.js#17]
Hi, I noticed you have the npm name "ecommerce" and it links to this repository. Would mind releasing the name? Or, if that's not possible please add me as an owner: `jonschlinkert`. Thanks!

**Comment by zeekay** [comment]
Hi! We've been reorganizing our projects and hadn't had a chance to publish a new version of our ecommerce template tool. I published a new version to fix the outdated links. Thanks!
